export const SET_DEFAULT_DATA = 'SET_DEFAULT_DATA';
export const INIT_DEFAULT_DATA = 'INIT_DEFAULT_DATA';
export const FETCH_DEFAULT_DATA_FAILED = 'FETCH_DEFAULT_DATA_FAILED';
export const POST_DEFAULT_DATA = 'POST_DEFAULT_DATA';
export const POST_DEFAULT_DATA_START = 'POST_DEFAULT_DATA_START';
export const POST_DEFAULT_DATA_SUCCESS = 'POST_DEFAULT_DATA_SUCCESS';
export const POST_DEFAULT_DATA_FAILED = 'POST_DEFAULT_DATA_FAILED';


export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const FETCH_PRIVATE_DATA_SUCCESS = 'FETCH_PRIVATE_DATA_SUCCESS'
export const FETCH_PRIVATE_DATA_FAIL = 'FETCH_PRIVATE_DATA_FAIL'
export const FETCH_PRIVATE_DATA_START = 'FETCH_PRIVATE_DATA_START'
export const FETCH_PRIVATE_DATA = 'FETCH_PRIVATE_DATA'

export const PURCHASE_BURGER = 'PURCHASE_BURGER';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';