export const FETCH_DEFAULT_DATA_SUCCESS = 'FETCH_DEFAULT_DATA_SUCCESS';
export const FETCH_DEFAULT_DATA_FAIL = 'FETCH_DEFAULT_DATA_FAIL';
export const FETCH_DEFAULT_DATA_START = 'FETCH_DEFAULT_DATA_START';
export const FETCH_DEFAULT_DATA = 'FETCH_DEFAULT_DATA';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAIL = 'FETCH_USER_DATA_FAIL';
export const FETCH_USER_DATA_START = 'FETCH_USER_DATA_START';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';

export const POST_USER_DATA = 'POST_USER_DATA';
export const POST_USER_DATA_START = 'POST_USER_DATA_START';
export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS';
export const POST_USER_DATA_FAILED = 'POST_USER_DATA_FAILED';

export const REMOVE_USER_CARD = 'REMOVE_USER_CARD';
export const REMOVE_USER_CARD_START = 'REMOVE_USER_CARD_START';
export const REMOVE_USER_CARD_SUCCESS = 'REMOVE_USER_CARD_SUCCESS';
export const REMOVE_USER_CARD_FAILED = 'REMOVE_USER_CARD_FAILED';

export const UPDATE_USER_CARD = 'UPDATE_USER_CARD';
export const UPDATE_USER_CARD_START = 'UPDATE_USER_CARD_START';
export const UPDATE_USER_CARD_SUCCESS = 'UPDATE_USER_CARD_SUCCESS';
export const UPDATE_USER_CARD_FAILED = 'UPDATE_USER_CARD_FAILED';

export const ADD_USER_DATA_ITEM = 'ADD_USER_DATA_ITEM';
export const ADD_USER_DATA_ITEM_TO_STATE = 'ADD_USER_DATA_ITEM_TO_STATE';
export const REMOVE_USER_DATA_ITEM = 'REMOVE_USER_DATA_ITEM';
export const UPDATE_USER_ITEM_DATA_PROPERTY = 'UPDATE_USER_ITEM_DATA_PROPERTY';

export const CREATE_USER_CARD = 'CREATE_USER_CARD';

